// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package costumers_db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Costumer struct {
	ID             int32
	Name           string
	Cpf            string
	Birthdate      time.Time
	Phone          string
	Email          string
	PhoneValidated bool
	EmailValidated bool
	Deleted        bool
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
}

type Outbox struct {
	ID          int64
	EventName   string
	Message     json.RawMessage
	CreatedAt   time.Time
	ProcessedAt sql.NullTime
}
